plugins:
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

title: Prathamesh Deshpande
description: Applied Researcher, Fujitsu Research India
show_navigation: true

theme: jekyll-theme-minimal
